import type {Metadata} from "next";
import "../globals.css";
import {ThemeProvider} from "@/components/theme-provider";
import {NextIntlClientProvider} from 'next-intl';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import {getMessages} from "next-intl/server";
import {Toaster} from "@/components/ui/sonner";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function LocaleLayout({
                                               params,
                                               children,
                                           }: {
    params: { locale: string }
    children: React.ReactNode
}) {
    const {locale} = await params
    if (!routing.locales.includes(locale)) {
        notFound()
    }
    const messages = await getMessages()
    return (
        <html lang={locale} suppressHydrationWarning>
        <body className="min-h-screen antialiased">
        <NextIntlClientProvider locale={locale} messages={messages}>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                {children}
                <Toaster/>
            </ThemeProvider>
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
